### ISSUE TITLE
ImportError: No module named '_SimpleITK'

### ISSUE THREAD

**Issue by Redzerman** [SuperElastix/SimpleElastix#120]
Hi Guys, 

I am trying to install SimpleElastix on my work PC but having an issue. I'm running Windows 7 and Winpython 3.4.4.6Qt5. When I run "python setup.py install" everything seems fines and SimpleElastix (1.0.0rc1.dev554+gd6eaa) appears in my pip list. 
However when I try to import SimpleITK into IPython or Spyder i get the following error:

import SimpleITK
Traceback (most recent call last):

  File "<ipython-input-1-f5d7554c860e>", line 1, in <module>
    import SimpleITK

  File "C:\Users\Developer\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\site-packages\SimpleITK\__init__.py", line 1, in <module>
    from .SimpleITK import *

  File "C:\Users\Developer\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\site-packages\SimpleITK\SimpleITK.py", line 17, in <module>
    _SimpleITK = swig_import_helper()

  File "C:\Users\Developer\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\site-packages\SimpleITK\SimpleITK.py", line 16, in swig_import_helper
    return importlib.import_module('_SimpleITK')

  File "C:\Users\Developer\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ImportError: No module named '_SimpleITK'

I performed the build on my laptop (Windows 10 and winpython 3.4.4.6Qt5), with CMake and visual studio 2017. SimpleElastix works fine on my laptop, but I need to get it working on my work PC. 
Any help is very much appreciated and thanks in advance.

**Comment by PertuyF** [comment]
Hi @Redzerman ,

Can't you rebuild on you work PC? Probably the simplest solution.

**Comment by Redzerman** [comment]
Hi PertuyF,

Thanks for the suggestion. 
Unfortunately I'm still waiting on the necessary privileges from our IT department in order to install CMake and Visual Studio on my work PC. I anticipate that additional privileges will be needed to perform the build also.

**Comment by TotteKarlsson** [comment]
Hello,
I'm having the same problem on a windows 7 computer. 
Any progress?

-tk

**Comment by rodrigomorenokth** [comment]
I had a similar problem and I realized that in order to have available SimpleElastix for Python 2 and 3, I have to compile SimpleElastix twice: once with the libraries of Python 2 (and then install it with python) and one with Python 3 (and then install it with python3). Now everything is working! Hopefully this can help others.

**Comment by cememreakbas** [comment]
I am having exactly the same issue as @senyuwang reported. How to fix it, any ideas??

**Comment by kaspermarstal** [comment]
Some people have experienced this issue when compiling against anaconda. Can you try to make 'regular' virtual environment (i.e. not conda), activate the virtualenv, and rebuild from scratch?
