### ISSUE TITLE
RuntimeError: Exception thrown in SimpleITK Elastix

### ISSUE THREAD

**Issue by salan668** [SuperElastix/SimpleElastix#132]
Hi, I installed the SimpleElastix and run it successfully by Python before. However, I recently can't use SimpleElastix. 

The code is like:
> fix_image = sitk.ReadImage('fix_image.nii')
moving_image = sitk.ReadImage('moving_image.nii')
result = sitk.Elastix(fix_image, moving_image)

There is a runtime error like:
> RuntimeError                              Traceback (most recent call last)
<ipython-input-16-c0c4328f3790> in <module>()
----> 1 result = sitk.Elastix(fix_image, moving_image)
C:\SimpleElastix\bulid\SimpleITK-build\Wrapping\Python\SimpleITK.py in Elastix(*args)
  10182     Elastix(Image fixedImage, Image movingImage, VectorOfParameterMap parameterMapVector, Image fixedMask, Image movingMask, bool const logToConsole=False, bool const logToFile=False, std::string const outputDirectory) -> Image
  10183     """
> 10184     return _SimpleITK.Elastix(*args)
  10185 class TransformixImageFilter(_object):
  10186     """Proxy of C++ itk::simple::TransformixImageFilter class."""
RuntimeError: Exception thrown in SimpleITK Elastix: C:\SimpleElastix\SimpleElastix\Code\Elastix\src\sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR: 
itk::ExceptionObject (00000049B3BE8960)
Location: "unknown" 
File: c:\simpleelastix\bulid\elastix\core\main\elxElastixFilter.hxx
Line: 248
Description: itk::ERROR: Self(00000214EB183B80): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).

It seems that I could use LogToConsole or LogToFile to get more informations. According to the error description, maybe I could set **logToConsole=True** in order to export the error information. But I can't set any propertiy of LogToConsole and have no idea how to export the log. 

Thank you.

**Comment by kaspermarstal** [comment]
Hi @salan668, run it like this:

```
result = sitk.Elastix(fix_image, moving_image, True)
```

**Comment by salan668** [comment]
Thanks, @kaspermarstal However, this still doesn't work. Similar Error like below:
>RuntimeError                              Traceback (most recent call last)
<ipython-input-3-959b1e5fd5d2> in <module>()
----> 1 result = sitk.Elastix(fix_image, moving_image, True)
C:\SY\SimpleElastix\bulid\SimpleITK-build\Wrapping\Python\SimpleITK.py in Elastix(*args)
  10182     Elastix(Image fixedImage, Image movingImage, VectorOfParameterMap parameterMapVector, Image fixedMask, Image movingMask, bool const logToConsole=False, bool const logToFile=False, std::string const outputDirectory) -> Image
  10183     """
> 10184     return _SimpleITK.Elastix(*args)
  10185 class TransformixImageFilter(_object):
  10186     """Proxy of C++ itk::simple::TransformixImageFilter class."""
RuntimeError: Exception thrown in SimpleITK Elastix: C:\SY\SimpleElastix\SimpleElastix\Code\Elastix\src\sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR: 
itk::ExceptionObject (00000026895E8DA0)
Location: "unknown" 
File: c:\sy\simpleelastix\bulid\elastix\core\main\elxElastixFilter.hxx
Line: 248
Description: itk::ERROR: Self(000001315D347B40): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()). 

Did I make anything woring during the installation? Thanks!

**Comment by kaspermarstal** [comment]
It doesn't show any other output? Running with `True` should log to console. This is all you see?

**Comment by kaspermarstal** [comment]
If you are using Spyder3 try running it in your terminal. The elastix logger does not work well with Spyder3.

**Comment by salan668** [comment]
Yes, this is all. I used the Python 3.5, (Anaconda 4.2) with Jupyter notebook. Here the fixed image was a 3D high-resolution image and moving image was a 3D low-resolution image. I found that if the fixed image and the moving image has similar resolution, SimpleElastix works. But if resolutions are different from each other, this error appears. 

Thank you!

**Comment by kaspermarstal** [comment]
Okay, well then, the error message that elastix throws probably has some very useful information for you then. You can also try to to LogToFile() if the console logger does not work. You can also try to run your code outside Jupyter. Anything to see the error message. Post the error message here when you get it and we can work from there!

**Comment by MLivy** [comment]
Hi, I have the exact same problem. I have scoured the internet unfortunately without any succes. Can anyone help?
Thanks in advance!


Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-342c7debb356>", line 1, in <module>
    resultImage = sitk.Elastix(sitk.ReadImage(r'G:\PsP vs TP\Test\True Progression\2020-02-18-002\IMAGES\IM00001'), sitk.ReadImage(r'G:\PsP vs TP\Test\True Progression\2020-02-18-002\IMAGES\IM00002'), True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\simpleitk-1.2.0rc2.dev1167+gd4cf2-py3.7-win-amd64.egg\SimpleITK\SimpleITK.py", line 11054, in Elastix
    return _SimpleITK.Elastix(*args)
RuntimeError: Exception thrown in SimpleITK Elastix: C:\Users\vctla\SimpleElastix\Code\Elastix\src\sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR: 
itk::ExceptionObject (0000004B63BEA6A0)
Location: "unknown" 

The IM00001 files are DICOM files.

**Comment by ctorti** [comment]
> 
> 
> Yes, this is all. I used the Python 3.5, (Anaconda 4.2) with Jupyter notebook. Here the fixed image was a 3D high-resolution image and moving image was a 3D low-resolution image. I found that if the fixed image and the moving image has similar resolution, SimpleElastix works. But if resolutions are different from each other, this error appears.
> 
> Thank you!

@salan668:  I am also having difficulties in trying to register images with two different resolutions.  And I'm also unable to get the errors to log to the console (in Jupyter notebook).  

Also, strangely, the logging to file only seems to work after each time I initialise the kernel in Jupyter.  If I re-execute the same cell (and re-create the error) the elastix.log file does not get updated.  Similarly if I get a new error from a different cell, the log file is not updated, rendering the log file not-so-useful.  I wonder if you were also experiencing this issue?

I'm wondering if, since you posted your query, have you had any success in working out how to register two images of varying resolutions?  And any fix for the failure for LogToConsoleOn() or LogToFileOn()? 

Thanks.

**Comment by salan668** [comment]
@ctorti : Actually I used another way to align images with differernt resolution: Complie the source code of Elastix and get the distributed file. Then you could use it in the command line. Also you could use it in python by sys module. 

Hope that will help.

**Comment by ctorti** [comment]
@salan668 : Thanks Suns.  Given that you decided to compile Elastix it looks like you may have decided to abandon SimpleElastix due to difficulties in trying to register images with very different resolutions.  

I'm curious to know:  Did you discover/determine that SimpleElastix has limitations that don't make it possible to do that, or is it that you simply took the path of least resistance?

**Comment by salan668** [comment]
@ctorti You're welcome. The complied Elastix works for me at that time (semms that 3 years ago?). I'm not sure how the SimpleElastix performs now.
