### ISSUE TITLE
Using `TransformixImageFilter` with `ThinPlateSpline`

### ISSUE THREAD

**Issue by b52** [SuperElastix/SimpleElastix#166]
Hej,

I can successfully register two images using `ThinPlateSpline` as in the following snippet:

```python
parameterMap = sitk.GetDefaultParameterMap("bspline")
parameterMap['Transform'] = ['SplineKernelTransform']
parameterMap['SplineKernelType'] = ['ThinPlateSpline']

parameterMapVector = sitk.VectorOfParameterMap()
parameterMapVector.append(parameterMap)

elastix = sitk.ElastixImageFilter()
elastix.SetParameterMap(parameterMapVector))
elastix.LogToConsoleOn()
elastix.PrintParameterMap()

elastix.SetFixedImage(image2_itk)
elastix.SetMovingImage(image_itk)
elastix.SetFixedPointSetFileName(points2_file)
elastix.SetMovingPointSetFileName(points1_file)
elastix.Execute()
```

However, when I additionally want to warp some points using `TransformixImageFilter` I get the following errors.

```python
transformixImageFilter = sitk.TransformixImageFilter()
params = elastix.GetTransformParameterMap()
transformixImageFilter.SetTransformParameterMap(params)
transformixImageFilter.SetOutputDirectory(tmpdir)
transformixImageFilter.SetFixedPointSetFileName(warp_file)
transformixImageFilter.Execute()
```

```
ELASTIX version: 4.801
Command line options from ElastixBase:
-out      /tmp/tmphtoish91/
-threads  unspecified, so all available threads are used
-def      /tmp/tmphtoish91/warppoints.pts
-jac      unspecified, so no det(dT/dx) computed
-jacmat   unspecified, so no dT/dx computed
Calling all ReadFromFile()'s ...
WARNING: The parameter "SplineKernelType", requested at entry number 0, does not exist at all.
  The default value "unknown" is used instead.
ERROR: the SplineKernelType is not given in the transform parameter file.

--------------- Exception ---------------

itk::ExceptionObject (0x563477c2daa0)
Location: "unknown"
File: /tmp/super/build/Elastix/Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.hxx
Line: 420
Description: itk::ERROR: SplineKernelTransform(0x563477e32eb0): ERROR: unable to configure transform.

-----------------------------------------
Traceback (most recent call last):
  File "displacement_map.py", line 234, in <module>
    warped_points = transform_elastix(image2, true_poss, warp_points)
  File "displacement_map.py", line 151, in transform_elastix
    transformixImageFilter.Execute()
  File "env/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 10453, in Execute
    return _SimpleITK.TransformixImageFilter_Execute(self)
RuntimeError: Exception thrown in SimpleITK TransformixImageFilter_Execute: /tmp/super/SimpleElastix/Code/Elastix/src/sitkTransformixImageFilterImpl.cxx:109:
sitk::ERROR:
itk::ExceptionObject (0x563477c2daa0)
Location: "unknown"
File: /tmp/super/build/Elastix/Core/Main/elxTransformixFilter.hxx
Line: 218
Description: itk::ERROR: Self(0x563475741730): Internal transformix error: See transformix log (use LogToConsoleOn() or LogToFileOn())
```

Apparently not all transform parameters are probably copied, or am I missing something? I assumed this is automatically handled?

**Comment by kaspermarstal** [comment]
Feel free to reopen if this is still an issue.
