### ISSUE TITLE
MultiThreader error: unable to create a thread

### ISSUE THREAD

**Issue by romangrothausmann** [SuperElastix/SimpleElastix#195]
When letting selx run multiple times (upto a few 1000 times in a for-loop), selx regularly crashes at a random number of iterations with a hint to look into the log-file, e.g. after successfully processing 766 of 1685 images (so far never reached the total of 2632 images without this problem):

```
   45.3% (764/1685) reg//001707_K2_0117_s00_05.tif 001708_K2_0117_s01_01.png 276.162473
   45.4% (765/1685) reg//001708_K2_0117_s01_01.tif 001709_K2_0117_s01_02.png 365.517457
   45.5% (766/1685) reg//001709_K2_0117_s01_02.tif 001710_K2_0117_s01_03.pngTraceback (most recent call last):
   File "../../../submodules//elastix/recRegStack.py", line 200, in <module>

    main()
  File "../../../submodules//elastix/recRegStack.py", line 100, in main
    register(FNs[start-1::-1], FNo, args, FNp)
  File "../../../submodules//elastix/recRegStack.py", line 180, in register
    selx.Execute()
  File "/opt/SimpleElastix/lib/python/SimpleITK-1.0.1rc1.dev347+g33a6b-py2.7-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 10132, in Execute
    return _SimpleITK.ElastixImageFilter_Execute(self)
RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /opt/SimpleElastix/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR:
itk::ExceptionObject (0x555aed2503b0)
Location: "unknown"
File: /opt/SimpleElastix_build/Elastix/Core/Main/elxElastixFilter.hxx
Line: 253
Description: itk::ERROR: Self(0x555aed2910a0): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).
```

The log-file then has an error such as:

```
749    301.785525    240.010000    0.123648    0.000012    0.9
Time spent in resolution 0 (ITK initialization and iterating): 1.263 s.
Stopping condition: Error in metric.
Settings of AdaptiveStochasticGradientDescent in resolution 0:
( SP_a 32.273438 )
( SP_A 20.000000 )
( SP_alpha 1.000000 )
( SigmoidMax 1.000000 )
( SigmoidMin -0.010000 )
( SigmoidScale 0.000000 )


itk::ExceptionObject (0x56114d3fc720)
Location: "ElastixTemplate - Run()"
File: /opt/SimpleElastix_build/ITK/Modules/Core/Common/src/itkMultiThreader.cxx
Line: 427
Description: itk::ERROR: MultiThreader(0x56114d23e1d0): Exception occurred during SingleMethodExecute
/opt/SimpleElastix_build/ITK/Modules/Core/Common/src/itkMultiThreaderPThreads.cxx:265:
itk::ERROR: MultiThreader(0x56114d23e1d0): Unable to create a thread.  pthread_create() returned 11

Error occurred during actual registration.
```

Even with a limited number of threads (e.g. SetNumberOfThreads(8)) or just 1 this problem occurs, but less frequently/likely.
I'm not sure whether the origin for this problem actually lies in ITK or selx, neither could I find a workaround from the OS/Linux side (though I did not try a custom compiled kernel where threading is disabled).

PS: Limiting the number of threads leads to a changed metric value, even if a grid sampler is used. This is expected though: https://groups.google.com/d/msg/elastix-imageregistration/FjkK5DE3Dvs/GbVKPfByAgAJ

**Comment by romangrothausmann** [comment]
I created a docker image with selx, in which the problem does not arise. So I guess it's a problem of the OS configuration/state (Debian 9.3). Any clues what could be the cause?

**Comment by kaspermarstal** [comment]
No idea, sorry.

**Comment by romangrothausmann** [comment]
Thanks for your reply. Seems to be one of these mysterious OS configuration problems. The solution with the docker image is sufficient for me.
