### ISSUE TITLE
ModuleNotFoundError: No module named '_SimpleITK'

### ISSUE THREAD

**Issue by pskeshu** [SuperElastix/SimpleElastix#226]
Hi,

I have trying to debug this for almost two days now, and I'm not sure why I'm not able to import SimpleITK. I think I might be missing something embarrassingly very obvious. Any help is appreciated.

```
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import SimpleITK
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/SimpleITK/SimpleITK.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib/python3.7/site-packages/SimpleITK/_SimpleITK.so: undefined symbol: PyInstance_Type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/SimpleITK/__init__.py", line 1, in <module>
    from .SimpleITK import *
  File "/usr/lib/python3.7/site-packages/SimpleITK/SimpleITK.py", line 17, in <module>
    _SimpleITK = swig_import_helper()
  File "/usr/lib/python3.7/site-packages/SimpleITK/SimpleITK.py", line 16, in swig_import_helper
    return importlib.import_module('_SimpleITK')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_SimpleITK'

```
I made sure cmake builds for python3.7, and I have tried compiling with gcc-5, 6 and 7, and there is a _SimpleITK.so along with the library, but SimpleITK throws the ModuleNotFoundError.

**Comment by kaspermarstal** [comment]
Have you tried to create a virtual environment, compile with that virtualenv enabled, installed in that virtual, and then loaded from there?

**Comment by kaspermarstal** [comment]
May be related: https://github.com/SuperElastix/SimpleElastix/issues/173
