### ISSUE TITLE
"Failed to allocate memory for image" error when reading Hamamatsu ndpi whole slide image

### ISSUE THREAD

**Issue by markemus** [SuperElastix/SimpleElastix#248]
I'm trying to load a [Hamamatsu formatted](https://openslide.org/formats/hamamatsu/) whole slide image (ndpi). It seems to be picking the TIFFImageIO correctly, but fails to load the image.

Is this actually a memory error, or is the ndpi format causing problems? The image is only 2.4 GB in size (possibly compressed) and I have 30 gb of available RAM and another 32 gb of swap memory. 

This is in 64 bit Python3, SimpleElastix version 1.1.0.dev355+g665d6. Compiled for Python3, installed with pip3.

```
f = sitk.ReadImage(fixed)
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65424 (0xff90) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65425 (0xff91) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65426 (0xff92) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65428 (0xff94) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65433 (0xff99) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65443 (0xffa3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65455 (0xffaf) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65456 (0xffb0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65457 (0xffb1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65459 (0xffb3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65424 (0xff90) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65425 (0xff91) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65426 (0xff92) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65428 (0xff94) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65433 (0xff99) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65443 (0xffa3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65455 (0xffaf) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65456 (0xffb0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65457 (0xffb1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65459 (0xffb3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65424 (0xff90) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65425 (0xff91) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65426 (0xff92) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65428 (0xff94) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65433 (0xff99) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65443 (0xffa3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65455 (0xffaf) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65456 (0xffb0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65457 (0xffb1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65459 (0xffb3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65424 (0xff90) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65425 (0xff91) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65426 (0xff92) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65428 (0xff94) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65433 (0xff99) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65443 (0xffa3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65455 (0xffaf) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65456 (0xffb0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65457 (0xffb1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65459 (0xffb3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65424 (0xff90) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65425 (0xff91) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65426 (0xff92) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65428 (0xff94) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65433 (0xff99) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65443 (0xffa3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65455 (0xffaf) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65456 (0xffb0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65457 (0xffb1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65459 (0xffb3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65424 (0xff90) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65425 (0xff91) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65426 (0xff92) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65428 (0xff94) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65433 (0xff99) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65443 (0xffa3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65455 (0xffaf) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65456 (0xffb0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65457 (0xffb1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65459 (0xffb3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65424 (0xff90) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65425 (0xff91) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65426 (0xff92) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65428 (0xff94) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65433 (0xff99) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65443 (0xffa3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65455 (0xffaf) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65456 (0xffb0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65457 (0xffb1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65459 (0xffb3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65450 (0xffaa) encountered.
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65421 (0xff8d) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65422 (0xff8e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65423 (0xff8f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65424 (0xff90) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65425 (0xff91) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65426 (0xff92) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65427 (0xff93) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65428 (0xff94) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65433 (0xff99) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65439 (0xff9f) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65440 (0xffa0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65441 (0xffa1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65442 (0xffa2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65443 (0xffa3) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65444 (0xffa4) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65445 (0xffa5) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65446 (0xffa6) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65449 (0xffa9) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65455 (0xffaf) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65456 (0xffb0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65457 (0xffb1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65459 (0xffb3) encountered.
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/markemus/.local/lib/python3.5/site-packages/SimpleITK/SimpleITK.py", line 8622, in ReadImage
    return _SimpleITK.ReadImage(*args)
RuntimeError: Exception thrown in SimpleITK ReadImage: /home/markemus/dev/SimpleElastix/build/ITK-prefix/include/ITK-4.13/itkImportImageContainer.hxx:199:
Failed to allocate memory for image.
```

**Comment by markemus** [comment]
The openslide specification mentions this:

> NDPI uses a TIFF-like structure, but libtiff cannot read the headers of an NDPI file. This is because NDPI specifies the RowsPerStrip as the height of the file, and after doing out the multiplication, this typically overflows libtiff and it refuses to open the file. Also, the TIFF tags are not stored in sorted order.

This seems to match the errors- both the `TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.`  error and the eventual overflow.

**Comment by kaspermarstal** [comment]
I take it this is an issue with the the ndpi format as you described. Feel free to reopen if this is not the case.
