### ISSUE TITLE
What are the reasons for the following problems and what are the solutions

### ISSUE THREAD

**Issue by zlf123-marker** [SuperElastix/SimpleElastix#327]
Traceback (most recent call last):
  File "gg.py", line 46, in <module>
    "translation")
  File "/home/zlf/anaconda3/lib/python3.6/site-packages/SimpleITK-1.2.0rc2.dev1162+g2a79d-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 11054, in Elastix
    return _SimpleITK.Elastix(*args)
RuntimeError: Exception thrown in SimpleITK Elastix: /home/zlf/SimpleElastix/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR: 
itk::ExceptionObject (0x55e850ef2180)
Location: "unknown" 
File: /home/zlf/SimpleElastix/build/Elastix/Core/Main/elxElastixFilter.hxx
Line: 253
Description: itk::ERROR: Self(0x55e850eafc00): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).

**Comment by kaspermarstal** [comment]
Hi @zlf123-marker, what does elastix print to console when you run with LogToConsoleOn()? (call elastixImageFilter.LogToConsoleOn() prior to running registration)

**Comment by zlf123-marker** [comment]
Thank you very much，I would like to ask whether CT and MR can be registered?This mistake can only occur when CT and MR are on time

**Comment by zlf123-marker** [comment]
Excuse me, I would also like to ask how to do registration for 4-dimensional data. SimpleElastix seems to report errors for 4-dimensional data as well
