### ISSUE TITLE
Error when use mask.

### ISSUE THREAD

**Issue by MSC19950601** [SuperElastix/SimpleElastix#344]
my code is:
parameterMap = sitk.GetDefaultParameterMap('translation')
parameterMap['ImageSampler'] = ['RandomSparseMask']

sitk.PrintParameterMap(parameterMap)

elastixFilter = sitk.ElastixImageFilter()
elastixFilter.LogToConsoleOn()
elastixFilter.SetFixedImage(fixed_image)
fixed_mask = sitk.Cast(fixed_mask, sitk.sitkUInt8)
fixed_mask.CopyInformation(fixed_mask)
elastixFilter.SetFixedMask(fixed_mask)
elastixFilter.SetMovingImage(moving_image)
moving_mask = sitk.Cast(moving_mask, sitk.sitkUInt8)
elastixFilter.SetMovingMask(moving_mask)
elastixFilter.SetParameterMap(parameterMap)
elastixFilter.Execute()

get problem:
itk::ExceptionObject (0x5559a1b83f60)
Location: "ElastixTemplate - Run()" 
File: /home/msc/med_extension/build/Elastix/Common/ImageSamplers/itkImageSamplerBase.hxx
Line: 402
Description: itk::ERROR: ImageGridSampler(0x5559a1b83700): ERROR: the bounding box of the mask lies entirely out of the InputImageRegion!

Error occurred during actual registration.

Traceback (most recent call last):
  File "/home/msc/WorkingProject/FLLMRI/registration/T1_ART_fixed_demo.py", line 231, in <module>
    elastixFilter.Execute()
  File "/home/msc/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/SimpleITK-1.2.0rc2.dev1162+g2a79d-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 10996, in Execute
    return _SimpleITK.ElastixImageFilter_Execute(self)
RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /home/msc/med_extension/SimpleElastix/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR: 
itk::ExceptionObject (0x5559a1b89f30)
Location: "unknown" 
File: /home/msc/med_extension/build/Elastix/Core/Main/elxElastixFilter.hxx
Line: 253
Description: itk::ERROR: Self(0x5559a1194fa0): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).

**Comment by kaspermarstal** [comment]
Maybe you mean `fixed_mask.CopyInformation(fixed_image)` instead of `fixed_mask.CopyInformation(fixed_mask)`? And make sure to do same with the moving mask. Let me know how it goes.

**Comment by MSC19950601** [comment]
Sitll have errors.
Here is code:
parameterMap = sitk.GetDefaultParameterMap('translation')
parameterMap['ImageSampler'] = ['RandomSparseMask']
#
sitk.PrintParameterMap(parameterMap)
#
elastixFilter = sitk.ElastixImageFilter()
elastixFilter.LogToConsoleOn()
elastixFilter.SetFixedImage(fixed_image)
fixed_mask = sitk.Cast(fixed_mask, sitk.sitkUInt8)
fixed_mask.CopyInformation(fixed_image)
elastixFilter.SetFixedMask(fixed_mask)
elastixFilter.SetMovingImage(moving_image)
moving_mask = sitk.Cast(moving_mask, sitk.sitkUInt8)
moving_mask.CopyInformation(moving_mask)
elastixFilter.SetMovingMask(moving_mask)
elastixFilter.SetParameterMap(parameterMap)
elastixFilter.Execute()

The error is: 
itk::ExceptionObject (0x564fddbeb130)
Location: "ElastixTemplate - Run()" 
File: /home/msc/med_extension/build/Elastix/Common/ImageSamplers/itkImageSamplerBase.hxx
Line: 402
Description: itk::ERROR: ImageGridSampler(0x564fddbfd160): ERROR: the bounding box of the mask lies entirely out of the InputImageRegion!

Error occurred during actual registration.


Traceback (most recent call last):
  File "/home/msc/WorkingProject/FLLMRI/registration/T1_ART_fixed_maskuse_demo.py", line 88, in <module>
    elastixFilter.Execute()
  File "/home/msc/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/SimpleITK-1.2.0rc2.dev1162+g2a79d-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 10996, in Execute
    return _SimpleITK.ElastixImageFilter_Execute(self)
RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /home/msc/med_extension/SimpleElastix/Code/Elastix/src/sitkElastixImageFilterImpl.cxx:259:
sitk::ERROR: 
itk::ExceptionObject (0x564fddbfd5e0)
Location: "unknown" 
File: /home/msc/med_extension/build/Elastix/Core/Main/elxElastixFilter.hxx
Line: 253
Description: itk::ERROR: Self(0x564fddbd5ea0): Internal elastix error: See elastix log (use LogToConsoleOn() or LogToFileOn()).

**Comment by kaspermarstal** [comment]
Can you write the mask to disk after the cast? I suspect that the masks are all zeros. This is the only thing I can think of that could cause this error.

**Comment by MSC19950601** [comment]
The mask value does not change after Cast. And here is the log
Self (0x5629bba02ed0)
  RTTI typeinfo:   elastix::ParameterObject
  Reference Count: 1
  Modified Time: 1566
  Debug: Off
  Object Name: 
  Observers: 
    none
ParameterMap 0: 
  (AutomaticParameterEstimation "true")
  (CheckNumberOfSamples "true")
  (DefaultPixelValue 0)
  (FinalBSplineInterpolationOrder 3)
  (FixedImagePyramid "FixedSmoothingImagePyramid")
  (ImageSampler "RandomSparseMask")
  (Interpolator "LinearInterpolator")
  (MaximumNumberOfIterations 256)
  (MaximumNumberOfSamplingAttempts 8)
  (Metric "AdvancedMattesMutualInformation")
  (MovingImagePyramid "MovingSmoothingImagePyramid")
  (NewSamplesEveryIteration "true")
  (NumberOfResolutions 4)
  (NumberOfSamplesForExactGradient 4096)
  (NumberOfSpatialSamples 2048)
  (Optimizer "AdaptiveStochasticGradientDescent")
  (Registration "MultiResolutionRegistration")
  (ResampleInterpolator "FinalBSplineInterpolator")
  (Resampler "DefaultResampler")
  (ResultImageFormat "nii")
  (Transform "EulerTransform")
  (WriteIterationInfo "false")
  (WriteResultImage "true")
