### ISSUE TITLE
Build error occurs in Ubuntu18.04, Anaconda python3.7

### ISSUE THREAD

**Issue by RishengDeng** [SuperElastix/SimpleElastix#387]
When I try to make the SuperBuild, the error occurs as follows,
I do not know how to solve the problem. The python version I am using is python3.7, and it is in the base enviroment of Anaconda, also it's the default python version in my computer path. 
```
[ 44%] Creating python virtual enviroment...
Already using interpreter /home/drs/anaconda3/bin/python
Not deleting /home/drs/opt/medical/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin
Using base prefix '/home/drs/anaconda3'
New python executable in /home/drs/opt/medical/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/bin/python
Installing setuptools, wheel...
  Complete output from command /home/drs/opt/medica...irtualenv/bin/python - setuptools wheel:
  Collecting setuptools
Exception:
Traceback (most recent call last):
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/adapters.py", line 184, in proxy_manager_for
    **proxy_kwargs
  File "/home/drs/opt/medical/build/virtualenv/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/adapters.py", line 43, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
pip._vendor.requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
----------------------------------------
...Installing setuptools, wheel...done.
CMake Error at PythonVirtualEnvInstall.cmake:38 (message):
  Creation of Python virtual environment failed.

  /home/drs/opt/medical/build/virtualenv/virtualenv.py:1039:
  DeprecationWarning: the imp module is deprecated in favour of importlib;
  see the module's documentation for alternative uses

    import imp

  Traceback (most recent call last):

    File "/home/drs/opt/medical/build/virtualenv/virtualenv.py", line 2328, in <module>
      main()
    File "/home/drs/opt/medical/build/virtualenv/virtualenv.py", line 713, in main
      symlink=options.symlink)
    File "/home/drs/opt/medical/build/virtualenv/virtualenv.py", line 945, in create_environment
      download=download,
    File "/home/drs/opt/medical/build/virtualenv/virtualenv.py", line 901, in install_wheel
      call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
    File "/home/drs/opt/medical/build/virtualenv/virtualenv.py", line 797, in call_subprocess
      % (cmd_desc, proc.returncode))

  OSError: Command /home/drs/opt/medica...irtualenv/bin/python - setuptools
  wheel failed with error code 2



Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/build.make:61: recipe for target 'Testing/Installation/PythonVirtualenv/bin/python' failed
make[5]: *** [Testing/Installation/PythonVirtualenv/bin/python] Error 1
make[5]: *** Deleting file 'Testing/Installation/PythonVirtualenv/bin/python'
CMakeFiles/Makefile2:3514: recipe for target 'Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all' failed
make[4]: *** [Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:119: recipe for target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:410: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kaspermarstal** [comment]
Hi @RishengDeng, the error happens earlier in another make thread, and that is why the install step fails. Try compiling with `make -j1` and post the new build log.
