### ISSUE TITLE
No module named '_SimpleITK'

### ISSUE THREAD

**Issue by jingxiweng** [SuperElastix/SimpleElastix#402]
Hi All,
I recently started working on image registration. I was trying to use SimpleElastix. However, I have tried on both Ubuntu and windows 10, but still I can't import it into python successfully. I also did what was on the tutorial (reinstall vc_redist), but it didn't work either. I have seen people previously posted almost same question, but still I can't figure out how I should solve it. 
Below is the error log. It is my first time to post an issue, sorry for any wrong format. 

import SimpleITK
Traceback (most recent call last):

  File "C:\Users\jwen0002\Anaconda3\lib\site-packages\simpleitk-2.0.0rc2.dev908+g8244e-py3.8-win-amd64.egg\SimpleITK\SimpleITK.py", line 14, in swig_import_helper
    return importlib.import_module(mname)

  File "C:\Users\jwen0002\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 556, in module_from_spec

  File "<frozen importlib._bootstrap_external>", line 1101, in create_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

ImportError: DLL load failed while importing _SimpleITK: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-2-16932c3140a0>", line 1, in <module>
    import SimpleITK

  File "C:\Users\jwen0002\Anaconda3\lib\site-packages\simpleitk-2.0.0rc2.dev908+g8244e-py3.8-win-amd64.egg\SimpleITK\__init__.py", line 1, in <module>
    from .SimpleITK import *

  File "C:\Users\jwen0002\Anaconda3\lib\site-packages\simpleitk-2.0.0rc2.dev908+g8244e-py3.8-win-amd64.egg\SimpleITK\SimpleITK.py", line 17, in <module>
    _SimpleITK = swig_import_helper()

  File "C:\Users\jwen0002\Anaconda3\lib\site-packages\simpleitk-2.0.0rc2.dev908+g8244e-py3.8-win-amd64.egg\SimpleITK\SimpleITK.py", line 16, in swig_import_helper
    return importlib.import_module('_SimpleITK')

  File "C:\Users\jwen0002\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named '_SimpleITK'

**Comment by jingxiweng** [comment]
By the way, now I am using a Windows system with anaconda, and there is no python2 installed. Is this error due to the version conflict between python 2 and python 3?

**Comment by lichy1988** [comment]
>>> import DicomRTTool
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    import DicomRTTool
  File "C:\Users\XSS\AppData\Roaming\Python\Python39\site-packages\DicomRTTool\__init__.py", line 6, in <module>
    import SimpleITK as sitk
  File "C:\Users\XSS\AppData\Roaming\Python\Python39\site-packages\SimpleITK\__init__.py", line 18, in <module>
    from SimpleITK.SimpleITK import *
  File "C:\Users\XSS\AppData\Roaming\Python\Python39\site-packages\SimpleITK\SimpleITK.py", line 13, in <module>
    from . import _SimpleITK
ImportError: DLL load failed while importing _SimpleITK: 找不到指定的模块。

**Comment by davidweioct** [comment]
Got the same issue: (Windows 10 + Visual studio 2019 + Anaconda3)

ImportError: DLL load failed while importing _SimpleITK: The specified module could not be found.

SimpleElastix used to work for me for the versions 1.5 year and 2 years ago for Linux.

**Comment by davidweioct** [comment]
It seems to be related to https://github.com/SuperElastix/SimpleElastix/issues/372
