### ISSUE TITLE
Install SE on Docker (Ubuntu 14.x) using anaconda.

### ISSUE THREAD

**Issue by tvessiere** [SuperElastix/SimpleElastix#87]
Hi everyone. 

I'm trying to install SE on a docker inside an anaconda environment. I followed the instructions on your website (git clone, cmake then install the python wrapping) and I have an error when i try to import SimpleITK: 
`>>> import SimpleITK as sitk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SimpleITK/__init__.py", line 1, in <module>
    from .SimpleITK import *
  File "SimpleITK/SimpleITK.py", line 17, in <module>
    _SimpleITK = swig_import_helper()
  File "SimpleITK/SimpleITK.py", line 16, in swig_import_helper
    return importlib.import_module('_SimpleITK')
  File "/root/anaconda2/envs/cytomine_itk/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _SimpleITK`

I tried it before on Ubuntu 16.04 classic desktop PC  and Cluster grid with (both inside an anaconda environment) and I never got any problems. 

Do you know where the problem could be ?

Thanks. 

Vessiere Thomas.

**Comment by PertuyF** [comment]
Hi @tvessiere 
Just checking, are you sure that Simple Elastix was installed for the right Python install or environment?
You can try `conda list` to see if SimpleITK is listed for the active Python environment.

**Comment by tvessiere** [comment]
Hi @PertuyF 

here is the result of `conda list` in Docker 
`(sel_itk) root@b64a95b25d0a:~# conda list
packages in environment at /root/anaconda2/envs/sel_itk:

bzip2                     1.0.6                         3  
cmake                     3.6.3                         0  
curl                      7.52.1                        0  
expat                     2.1.0                         0  
freetype                  2.5.5                         1    anaconda
geos                      3.4.2                         4    scitools
hdf5                      1.8.17                        1    anaconda
jbig                      2.1                           0    anaconda
joblib                    0.9.4                    py27_0    anaconda
jpeg                      9b                            0  
libgfortran               3.0.0                         1    anaconda
libjpeg-turbo             1.2.0                         0    meawoppl
libpng                    1.6.27                        0    anaconda
libtiff                   4.0.6                         3  
mkl                       2017.0.1                      0    anaconda
ncurses                   5.9                          10  
numpy                     1.11.3                   py27_0    anaconda
olefile                   0.44                     py27_0  
openblas                  0.2.14                        4    anaconda
openslide-python          1.1.0                    py27_0    cdeepakroy
openssl                   1.0.2k                        1    anaconda
pillow                    4.1.0                    py27_0  
pip                       9.0.1                    py27_1    anaconda
python                    2.7.13                        0    anaconda
readline                  6.2                           2    anaconda
scipy                     0.19.0              np111py27_0    anaconda
setuptools                27.2.0                   py27_0    anaconda
shapely                   1.5.16                   py27_0    anaconda
SimpleElastix             1.0.0rc1.dev547+g12d1c           <pip>
simpleitk                 1.0.0                    py27_0    simpleitk
sqlite                    3.13.0                        0    anaconda
tk                        8.5.18                        0    anaconda
wheel                     0.29.0                   py27_0    anaconda
xz                        5.2.2                         1    anaconda
zlib                      1.2.8                         3    anaconda
`
simpleitk is listed because I installed it using its conda package. If I try to install SimpleElastix without the simpleitk conda package, SimpleElastix is listed, but not SimpleITK. Both approaches lead me to the same error I showed above. The conda simpleitk package seems to work fine when SimpleElastix is not installed.

Here is the conda list result from my Desktop PC sel_itk (ubuntu 16.04) environment : 
`(sel_itk) tvessiere@rmtower:$ conda list# packages in environment at /home/tvessiere/data/miniconda2/envs/sel_itk:
#
freetype                  2.5.5                         1  
geos                      3.4.2                         4    scitools
hdf5                      1.8.17                        1  
jbig                      2.1                           0  
joblib                    0.9.4                    py27_0    anaconda
jpeg                      8d                            2  
libgfortran               3.0.0                         1    anaconda
libjpeg-turbo             1.2.0                         0    meawoppl
libpng                    1.6.27                        0  
libtiff                   4.0.6                         2  
mkl                       2017.0.1                      0    anaconda
numpy                     1.11.3                   py27_0  
openblas                  0.2.14                        4  
opencv                    3.1.0               np111py27_1  
openslide-python          1.1.0                    py27_0    cdeepakroy
openssl                   1.0.2k                        1  
pillow                    3.4.2                    py27_0  
pip                       9.0.1                    py27_1  
python                    2.7.13                        0  
readline                  6.2                           2  
scipy                     0.19.0              np111py27_0  
setuptools                27.2.0                   py27_0  
shapely                   1.5.16                   py27_0  
SimpleElastix             0.10.0rc1.dev812+g7e302           <pip>
sldc                      1.0                       <pip>
sldc-openslide            1.0                       <pip>
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
`
simpleitk is not listed but SimpleITK and SimpleElastix works fine.

Thanks for your help,

Vessiere Thomas

**Comment by PertuyF** [comment]
@tvessiere 
I see that it is installed in a conda env called "sel_itk". Can you check that you're actually calling the python linked to this specific environment?
With linux having a system python install I know conflicts can occur where `python` command is still linked to the system install (usr/bin/python) instead of your conda install.

You can either use `which python` or just call `python` and see if there is any mention of "Continuum analytics" or "conda-forge" next to the python version.

**Comment by kaspermarstal** [comment]
Closing due to lack of activity. Feel free to reopen if needed!

**Comment by GhadirAbuRisha** [comment]
Hi @tvessiere,
How did you install SE to anaconda? I tired installing SE using the installation guide on their website with seemingly no problems, but when I check with conda list neither SimpleITK (or simpleitk) nor SimpleElastix is installed! when I check with pip3 list only SimpleITK is there. Sorry if the question is too naive, but I'm new to this and I'm not sure what I'm doing wrong.
Thanks in advance,
Ghadir
